import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Oxygen } from "next/font/google";
import Header from "@/components/layout/header";
import AppCartProvider from "@/components/shop/app-cart-provider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });
const oxygem = Oxygen({ weight: ["300", "400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(oxygem.className, "min-h-screen flex flex-col")}>
        <AppCartProvider>
          <Header />
          <main className="flex-grow">{children}</main>
          <Toaster />
        </AppCartProvider>
      </body>
    </html>
  );
}
